### ISSUE TITLE
Can't update to Autoform 5

### ISSUE THREAD

**Issue by jshimko** [comerc/meteor-autoform-selectize#10]
Just wanted to point out that installing this package prevents you from being able to update to [Autoform 5][1].  (currently [restricted to 4.0.0](https://github.com/comerc/meteor-autoform-selectize/blob/master/package.js#L12))

[1]: https://github.com/aldeed/meteor-autoform/blob/master/CHANGELOG.md

**Comment by lucatros** [comment]
I second this request.
Any chance on updating it to autoform 5? 
If you can just update the api.use section I can test it and confirm everything is working.

Thanks!

**Comment by jfly** [comment]
+1

**Comment by JoshuaNovak919** [comment]
Any update on when this will be update?

**Comment by mgruen** [comment]
+1

**Comment by jshimko** [comment]
I already fixed this.  Pull request is waiting to be merged. 

https://github.com/comerc/meteor-autoform-selectize/pull/11

**Comment by maxnowack** [comment]
+1

**Comment by tcastelli** [comment]
+1

**Comment by jshimko** [comment]
Since this was preventing Autoform updates and I use it in several apps, I went ahead and published my own package to fix the version constraint.  For anyone interested...

```bash
meteor add jeremy:autoform-selectize
```
https://github.com/jshimko/meteor-autoform-selectize
https://atmospherejs.com/jeremy/autoform-selectize

Note that this now depends on my `jeremy:selectize` package and will install it automatically.

Sorry @comerc, I certainly don't mean to steal your thunder here.  I just really needed this update to happen.  :)  Thank you for your work on this!

**Comment by efounders** [comment]
Thanks @jshimko for the fork/update.

**Comment by acemtp** [comment]
@jshimko thanks for the fork/update!

**Comment by roelvan** [comment]
@jshimko thanks mate

**Comment by ricardodovalle** [comment]
@jshimko thank you very much :+1:

**Comment by udnaan** [comment]
Thanks @jshimko for the fork

**Comment by comerc** [comment]
@jshimko, it is not fork, but copy. I dont see changes for merge. Very bad. Bugs also duplicated. :)
